on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'
        required: true
        type: string
  workflow_call:
    inputs:
      test:
        description: 'test'
        required: true
        type: string

jobs:
  level-1-on-repo-1-initial-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: level-1 on repo-1
        run: |
          echo "level-1 on repo-1 ${{ github.event.inputs.test }}"

  level-1-on-repo-1:
    uses: ./.github/workflows/level-2.yaml
