on:
  workflow_dispatch:
  workflow_call:

jobs:
  level-1-on-repo-1-initial-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: level-1 on repo-1
        run: |
          echo "level-1 on repo-1"

  level-1-on-repo-1:
    uses: ./.github/workflows/level-2.yaml
